#!/usr/bin/env python3
"""
Copy the published documents out of the source repositories into docs/.

Usage:
    python tools/sync_docs.py [--check]

docs/ is committed so that GitHub renders it without access to the private
sources. --check reports what would change and returns non-zero instead of
writing, for use before tagging a release.

Documents that were co-located in doc/ stay co-located under docs/<key>/,
so links between them keep working; links that pointed into a private
source tree are unlinked via manifest.LINK_REWRITE.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import manifest

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")


def rewrite_links(text, src_label):
    unknown = set()

    def repl(m):
        label, target = m.group(1), m.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return m.group(0)
        if target in manifest.LINK_REWRITE:
            new = manifest.LINK_REWRITE[target]
            return label if new is None else f"[{label}]({new})"
        if target.startswith(("../", "/")) or "/" in target:
            unknown.add(target)
        return m.group(0)

    out = LINK_RE.sub(repl, text)
    for target in sorted(unknown):
        print(f"WARNING: {src_label}: link leaves the copy and has no "
              f"rewrite rule: {target}")
    return out


def render(entry, src_rel, dst_rel):
    src = manifest.abspath(entry["path"], src_rel)
    with open(src, "r", encoding="utf-8") as f:
        text = f.read()
    text = rewrite_links(text, f"{entry['key']}/{os.path.basename(src_rel)}")
    banner = (f"<!-- generated by tools/sync_docs.py from "
              f"{entry['path']}/{src_rel} - do not edit here -->\n")
    return banner + text


def index():
    lines = ["# ドキュメント", "",
             "MSX Sound Suite Extension に含まれる各拡張BASICの仕様書。", ""]
    for key, title in manifest.DOC_SECTIONS:
        entry = manifest.repo(key)
        lines += [f"## {title}", ""]
        for _, dst_rel, label in entry["docs"]:
            lines.append(f"- [{label}]({dst_rel})")
        lines.append("")
    lines += ["## 開発", ""]
    for dst_rel, label in manifest.LOCAL_DOCS:
        lines.append(f"- [{label}]({dst_rel})")
    lines.append("")
    return "\n".join(lines)


def write(path, text, check):
    full = manifest.abspath(manifest.DOCS, path)
    old = None
    if os.path.isfile(full):
        with open(full, "r", encoding="utf-8", newline="") as f:
            old = f.read()
    if old == text:
        print(f"    {path} (unchanged)")
        return False
    if check:
        print(f"    {path} (OUT OF DATE)")
        return True
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"    {path} ({'updated' if old is not None else 'new'})")
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="report staleness without writing")
    args = parser.parse_args()

    stale = False
    for entry in manifest.REPOS:
        print(f"=== {entry['title']} ===")
        for src_rel, dst_rel, _ in entry["docs"]:
            src = manifest.abspath(entry["path"], src_rel)
            if not os.path.isfile(src):
                print(f"ERROR: missing {entry['path']}/{src_rel} "
                      f"(git submodule update --init)")
                return 1
            stale |= write(dst_rel, render(entry, src_rel, dst_rel), args.check)
    print("=== index ===")
    stale |= write("README.md", index(), args.check)

    if args.check and stale:
        print("\ndocs/ is out of date; run tools/sync_docs.py")
        return 1
    print("\nOK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
